/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-06-14 02:35:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.SinhVien;
import model.BangDiem;
import model.Diem;
import service.BangDiemService;

public final class XemDiemThi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Diem");
    _jspx_imports_classes.add("service.BangDiemService");
    _jspx_imports_classes.add("model.BangDiem");
    _jspx_imports_classes.add("model.SinhVien");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Cổng thông tin đào tạo Học viện Công nghệ Bưu chính Viễn thông</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"../res/main-css.css\">\n");
      out.write("        ");
 SinhVien sinhVien = (SinhVien) session.getAttribute("maSinhVien");
            if (sinhVien == null) {
                response.sendRedirect("../Views/login.jsp");
            } 
      out.write("\n");
      out.write("\n");
      out.write("        <style>\n");
      out.write("            table {\n");
      out.write("                border: 2px solid black;\n");
      out.write("                border-collapse: collapse;\n");
      out.write("                height: 5px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            th, td {\n");
      out.write("                border: 2px solid black;\n");
      out.write("                border-collapse: collapse;\n");
      out.write("            \n");
      out.write("            }\n");
      out.write("            th{\n");
      out.write("                padding-left: 5px;\n");
      out.write("                padding-right: 5px;\n");
      out.write("            }\n");
      out.write("            table tr:nth-child(odd){\n");
      out.write("            background-color:#eee;\n");
      out.write("            }\n");
      out.write("            table tr:nth-child(even){\n");
      out.write("                background-color:white;\n");
      out.write("            }\n");
      out.write("            table tr:nth-child(1){\n");
      out.write("                background-color:skyblue;\n");
      out.write("            }\n");
      out.write("      \n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body><div id=\"header\">\n");
      out.write("            <div id=\"h1\"></div>\n");
      out.write("            <div id=\"h2\">\n");
      out.write("                ");
 if (sinhVien == null) {
      out.write("\n");
      out.write("                <button onclick=\"window.location.href = 'Views/login.jsp'\">Đăng nhập</button>\n");
      out.write("                ");
 } else {
      out.write("\n");
      out.write("                <span style=\"color: yellow; font-weight: bolder\">\n");
      out.write("                    Chào bạn, ");
      out.print( sinhVien.getHoTen());
      out.write("&nbsp;(");
      out.print( sinhVien.getMaSV());
      out.write(") \n");
      out.write("                </span> <button><a style=\"text-decoration: none\" href=\"/logout\">Đăng xuất</a></button>\n");
      out.write("                ");
 }
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("            <div id=\"content\" >\n");
      out.write("            <div id=\"menu\">\n");
      out.write("                <a class=\"menu-items\" href=\"../index.jsp\">TRANG CHỦ</a>\n");
      out.write("                <a class=\"menu-items\" href=../Views/XemDiemThi.jsp>XEM KẾT QUẢ HỌC TẬP</a>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"main-content\">\n");
      out.write("                <div style=\"margin-left: 35%; margin-right: 43%\">\n");
      out.write("                    ");
 if (sinhVien != null) {
      out.write("\n");
      out.write("                    <p style=\"border-style: double;\">\n");
      out.write("                        Họ và tên : ");
      out.print( sinhVien.getHoTen());
      out.write("<br>\n");
      out.write("                        Mã sinh viên : ");
      out.print( sinhVien.getMaSV());
      out.write("<br>\n");
      out.write("                        Lớp : ");
      out.print( sinhVien.getLop());
      out.write("<br>\n");
      out.write("                        Khóa : ");
      out.print( sinhVien.getKhoaHoc());
      out.write("<br>\n");
      out.write("                        Hệ đào tạo : ");
      out.print( sinhVien.getHeDaoTao());
      out.write("<br>\n");
      out.write("                        Khoa : ");
      out.print( sinhVien.getKhoa());
      out.write("<br>\n");
      out.write("                        Ngành : ");
      out.print( sinhVien.getNganh());
      out.write("\n");
      out.write("                    </p>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        <a href=\"../Views/XemDiemThi.jsp?hocKy=all\" style=\"color: black; margin-left: 15%\">Xem toàn bộ kết quả học tập</a>\n");
      out.write("                    <br>\n");
      out.write("                    <br>\n");
      out.write("                </div>\n");
      out.write("                <div style=\"margin-left: 32%\">\n");
      out.write("                    <form action=\"/Views/XemDiemThi.jsp\" method=\"GET\">\n");
      out.write("                        <input type=\"text\" size=\"65\" name=\"hocKy\" placeholder=\"Nhập học kỳ xem điểm thi, vd 20161-Kỳ 1 năm 2016...\">\n");
      out.write("                        <input type=\"submit\" value=\"Tìm kiếm\">\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("                <br>\n");
      out.write("                ");
 String hocKy = request.getParameter("hocKy");
                    if (hocKy != null && !hocKy.isEmpty()) {
                
      out.write("\n");
      out.write("                ");
 if(!hocKy.equals("all")){
                
      out.write("\n");
      out.write("                <p style=\"margin-left: 40px\">Học kỳ ");
      out.print( hocKy.substring(4) );
      out.write(" Năm học ");
      out.print( hocKy.substring(0,4) );
      out.write(" </p>\n");
      out.write("                ");
 }
                
      out.write("\n");
      out.write("                <table style=\"margin-left: 40px; overflow: auto\">\n");
      out.write("                    <tr style=\"font-weight: normal; font-style: normal; background-color: darkgray; \">\n");
      out.write("                        <th>STT</th>\n");
      out.write("                        <th>Mã môn</th>\n");
      out.write("                        <th>Tên môn</th>\n");
      out.write("                        <th>TC</th>\n");
      out.write("                        <th>%CC</th>\n");
      out.write("                        <th>%KT</th>\n");
      out.write("                        <th>%TH</th>\n");
      out.write("                        <th>%BT</th>\n");
      out.write("                        <th>%Thi</th>\n");
      out.write("                        <th>Điểm CC</th>\n");
      out.write("                        <th>Điểm KT</th>\n");
      out.write("                        <th>Điểm TH</th>\n");
      out.write("                        <th>Điểm BT</th>\n");
      out.write("                        <th>Thi L1</th>\n");
      out.write("                        <th>Thi L2</th>\n");
      out.write("                        <th>TK(10)</th>\n");
      out.write("                        <th>TK(CH)</th>\n");
      out.write("                        <th>KQ</th>\n");
      out.write("                        <th>Môn TL</th>\n");
      out.write("                    </tr>\n");
      out.write("                    ");
 BangDiemService bangDiemService = new BangDiemService();
                        BangDiem bangDiem = bangDiemService.getBangDiem("B16DCCN001", hocKy);
                        int stt = 1;
                        for (Diem i : bangDiem.getDiems()) {
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                        <td>");
      out.print( stt);
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getHocPhan().getMa());
      out.write("</td>\n");
      out.write("                        <td style=\"text-align: left\">");
      out.print( i.getHocPhan().getTen());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getHocPhan().getSoTC());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getpCC());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getpKT());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getpTH());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getpBT());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getpThi());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getCc());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getKt());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getTh());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getBt());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getThiL1());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getThiL2());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getTkHe10());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getTkHeChu());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getKQ());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( i.getHocPhan().getMonTL());
      out.write("</td\n");
      out.write("                    </tr>\n");
      out.write("                    ");
  stt++;
                        }
                    
      out.write("\n");
      out.write("                </table>\n");
      out.write("                    <p style=\"margin-left: 40px\">Số tín chỉ đạt: ");
      out.print( bangDiem.getSoTinChiDat());
      out.write("</p>\n");
      out.write("                    <p style=\"margin-left: 40px\">Điểm trung bình học kỳ hệ 4 : ");
      out.print( bangDiem.getTbHocKyHe4());
      out.write("</p>\n");
      out.write("                    <p style=\"margin-left: 40px\">Số tín chỉ tích lũy : ");
      out.print( bangDiem.getSoTinChiTichLuy());
      out.write("</p>\n");
      out.write("                    <p style=\"margin-left: 40px\">Điểm trung bình tích lũy hệ 4 : ");
      out.print( bangDiem.getTbTichLuyHe4());
      out.write("</p>\n");
      out.write("                    <p style=\"margin-left: 40px\">Đánh giá: ");
      out.print( bangDiem.getDanhGia());
      out.write("</h3>\n");
      out.write("                ");
}
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"footer\">\n");
      out.write("            <br>\n");
      out.write("            <h3 style=\"margin-left: 5%\">HỌC VIỆN CÔNG NGHỆ BƯU CHÍNH VIỄN THÔNG</h3>\n");
      out.write("            <div id=\"footer11\">\n");
      out.write("                <div id=\"beginfooter\"></div>\n");
      out.write("                <div id=\"footer1\">\n");
      out.write("                    <p style=\"margin-bottom: 0px;\">Trụ sở chính:</p>\n");
      out.write("                    <p style=\"margin-top: 0px;\">122 Hoàng Quốc Việt, Q.Cầu Giấy, Hà Nội.</p>\n");
      out.write("                    <p style=\"margin-bottom: 0px;\">Cơ sở đào tạo tại Hà Nội:</p>\n");
      out.write("                    <p style=\"margin-top: 0px;\">Km10, Đường Nguyễn Trãi, Q.Hà Đông, Hà Nội</p>  \n");
      out.write("                    <a href=\"https://www.facebook.com/HocvienPTIT\"><img class=\"contactIcon\" src=\"../res/fbb.png\" style=\"border-radius: 5px\"></a>\n");
      out.write("                    <a href=\"http://portal.ptit.edu.vn/\"><img class=\"contactIcon\" src=\"../res/ptit.png\"></a>\n");
      out.write("                   \n");
      out.write("                </div>\n");
      out.write("                <div id=\"footer2\">\n");
      out.write("                    <p style=\"margin-bottom: 0px;\">Học viện cơ sở tại TP. Hồ Chí Minh:</p>\n");
      out.write("                    <p style=\"margin-top: 0px;\">11 Nguyễn Đình Chiểu, P. Đa Kao, Q.1 TP Hồ Chí Minh</p>\n");
      out.write("                    <p style=\"margin-bottom: 0px;\">Cơ sở đào tạo tại TP Hồ Chí Minh:</p>\n");
      out.write("                    <p style=\"margin-top: 0px;\">Đường Man Thiện, P. Hiệp Phú, Q.9 TP Hồ Chí Minh</p>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("                <div id=\"footer3\">\n");
      out.write("                    <br>\n");
      out.write("                    <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3725.301678832317!2d105.78570991486083!3d20.98054088602447!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135acce762c2bb9%3A0xbb64e14683ccd786!2zSOG7jWMgdmnhu4duIEPDtG5nIG5naOG7hyBCxrB1IGNow61uaCBWaeG7hW4gdGjDtG5nIC0gUFRJVA!5e0!3m2!1svi!2s!4v1585330320219!5m2!1svi!2s\"\n");
      out.write("                            width=\"400\" height=\"100\" frameborder=\"0\" style=\"border:0;\" allowfullscreen=\"\" aria-hidden=\"false\" tabindex=\"0\"></iframe>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>        \n");
      out.write("    </body>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
